version: '3.8'

services:
  service-a:
    build:
      context: .
      dockerfile: service.Dockerfile
    volumes:
      - ./model-weights-a:/app/model-data
    environment:
      - MODEL_FOLDER=/app/model-data
      - SERVICE_NAME=service-a
      - PYTHONUNBUFFERED=1
    ports:
      - "8083:8082"
    networks:
      - app-network

  service-b:
    build:
      context: .
      dockerfile: service.Dockerfile
    volumes:
      - ./model-weights-b:/app/model-data
    environment:
      - MODEL_FOLDER=/app/model-data
      - SERVICE_NAME=service-b
      - PYTHONUNBUFFERED=1
    ports:
      - "8084:8082"
    networks:
      - app-network

  load-balancer:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVICE_A_URL=http://service-a:8082
      - SERVICE_B_URL=http://service-b:8082
    depends_on:
      - service-a
      - service-b
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
